name       : libnumbertext
version    : 1.0.4
release    : 1
source     :
    - git|https://github.com/Numbertext/libnumbertext : 2adc5b7f5232b63653737f776c2bad20a909f154
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
component  : programming.library
summary    : Number to number name and money text conversion libraries
description: |
    Language-neutral NUMBERTEXT and MONEYTEXT functions for LibreOffice Calc
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
