name       : libnumbertext
version    : 1.0.6
release    : 2
source     :
    - https://github.com/Numbertext/libnumbertext/releases/download/1.0.6/libnumbertext-1.0.6.tar.xz : 739f220b34bf7cb731c09de2921771d644d37dfd276c45564401e5759f10ae57
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
component  : programming.library
summary    : Number to number name and money text conversion libraries
description: |
    Language-neutral NUMBERTEXT and MONEYTEXT functions for LibreOffice Calc
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
